CREATE TABLE CTHD (
    SOHD NUMBER NOT NULL,
    MASP NUMBER NOT NULL,
    SOLUONG NUMBER NOT NULL,
    CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MASP)
)

--INSERT DATA
SELECT * FROM CTHD;

INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(1, 137, 1); --Sản phẩm là bó hồng AOI, sau khi bán đi slsan của sp này từ 8 còn 7
INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(1, 162, 1); --Sản phẩm là thiệp CHÚC MỘT NGÀY TỐT LANH, sau khi bán đi slsan của sp này từ 60 còn 59
INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(2, 73, 3); --Sản phẩm là đào sakura trắng loại II, sau khi bán đi slsan của sp này từ 30 còn 27 
INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(2, 158, 1); --Sản phẩm là bình hoa gốm Biên Hòa xưa, sau khi bán đi slsan từ 1 về 0.
INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(3, 20, 10);
INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(4, 50, 5);
INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(5, 55, 1);
INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(5, 90, 3);
INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(6, 127, 1);
INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(7, 20, 10);
INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(8, 2, 5);
INSERT INTO CTHD(SOHD,MASP,SOLUONG) VALUES(8, 121, 1);

COMMIT;
--thành công