CREATE TABLE CTKM (
    SOHD NUMBER NOT NULL,
    MAKM NUMBER NOT NULL,
    CONSTRAINT PK_CTKM PRIMARY KEY (SOHD, MAKM)
)

--INSERT DATA
SELECT * FROM CTKM;
INSERT INTO CTKM(SOHD, MAKM) VALUES(1, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(2, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(3, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(4, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(5, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(6, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(7, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(8, 2);

COMMIT;


