CREATE TABLE KHACHHANG (
    MAKH NUMBER NOT NULL,
    HOTEN NVARCHAR2(50) NOT NULL,
    SDT VARCHAR2(20) NOT NULL UNIQUE,
    DIACHI NVARCHAR2(255) NULL,
    NGAYSINH DATE NOT NULL,
    NGAYDK DATE NOT NULL,
    LOAIKH VARCHAR2(20) DEFAULT N'Binh thuong',
    TICHLUY NUMBER DEFAULT 0,
    GHICHU NVARCHAR2(255),
    GIOITINH NVARCHAR2(10) NOT NULL,
    CONSTRAINT PK_KH PRIMARY KEY(MAKH)
)
CREATE SEQUENCE SEQ1_MAKH START WITH 1;
SELECT * FROM khachhang;
--INSERT DATA
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
INSERT INTO KHACHHANG(MAKH,HOTEN,SDT,DIACHI,NGAYSINH,GHICHU,GIOITINH) VALUES (SEQ1_MAKH.NEXTVAL,N'Nguyễn Văn Anh','0912373899',N'234 Đ. Tô Ngọc Vân, P.Linh Chiểu, TP. Thủ Đức, TP. Hồ Chí Minh','22/02/1998',NULL,'Nam');
INSERT INTO KHACHHANG(MAKH,HOTEN,SDT,DIACHI,NGAYSINH,GHICHU,GIOITINH) VALUES (SEQ1_MAKH.NEXTVAL,N'Lê Thị Ngọc Mai','0979132947',N'87 Đ. Lê Văn Duyệt , Phường 3, Quận Bình Thạnh, TP. Hồ Chí Minh','12/03/2000',NULL,'Nữ');
INSERT INTO KHACHHANG(MAKH,HOTEN,SDT,DIACHI,NGAYSINH,GHICHU,GIOITINH) VALUES (SEQ1_MAKH.NEXTVAL,N'Phan Thị Kim Oanh','0984287811',N'1128 Đ. Kha Vạn Cân, P.Linh Chiểu, TP. Thủ Đức, TP. Hồ Chí Minh','30/12/1995',NULL,'Nữ');
INSERT INTO KHACHHANG(MAKH,HOTEN,SDT,DIACHI,NGAYSINH,GHICHU,GIOITINH) VALUES (SEQ1_MAKH.NEXTVAL,N'Khương Hằng Nga','0914609066',N'365 Đ. Kha Vạn Cân, P. Hiệp Bình Chánh, TP. Thủ Đức, TP. Hồ Chí Minh','21/04/1997',N'Không xịt mùi hương vào hoa','Nữ');
INSERT INTO KHACHHANG(MAKH,HOTEN,SDT,DIACHI,NGAYSINH,GHICHU,GIOITINH) VALUES (SEQ1_MAKH.NEXTVAL,N'Dương Thị Hồng Thắm','0975025199',N'226 Đ. Nguyễn Thái Sơn, Phường 3, Quận Gò Vấp, TP. Hồ Chí Minh','03/05/1989',NULL,'Nữ');
INSERT INTO KHACHHANG(MAKH,HOTEN,SDT,DIACHI,NGAYSINH,GHICHU,GIOITINH) VALUES (SEQ1_MAKH.NEXTVAL,N'Vũ Thị Mai Thoa','0967701212',N'965 Đ. Quang Trung, Phường 14, Quận Gò Gấp, TP. Hồ Chí Minh','11/09/1990',N'Liên hệ khách hàng khi vừa nhập hoa hồng Pháp','Nữ');
INSERT INTO KHACHHANG(MAKH,HOTEN,SDT,DIACHI,NGAYSINH,GHICHU,GIOITINH) VALUES (SEQ1_MAKH.NEXTVAL,N'Trương Thúy Hằng','0869516563',N'123/6 Đ. Cao Thắng, Phường 17, Quận Phú Nhuận, TP. Hồ Chí Minh','18/09/1999',NULL,'Nữ');
INSERT INTO KHACHHANG(MAKH,HOTEN,SDT,DIACHI,NGAYSINH,GHICHU,GIOITINH) VALUES (SEQ1_MAKH.NEXTVAL,N'Đặng Ngọc Sơn','0967771212',N'12 Đường số 4, P. Tăng Nhơn Phú B, TP. Thủ Đức, TP. Hồ Chí Minh','05/12/2001',NULL,'Nam');

COMMIT;
--thành công