CREATE TABLE LOAISANPHAM (
    MALOAISP NUMBER NOT NULL,
    TENLOAISP NVARCHAR2(100) NOT NULL UNIQUE,
    GHICHU NVARCHAR2(255),
    CONSTRAINT PK_LOAISP PRIMARY KEY(MALOAISP)
)

CREATE SEQUENCE SEQ8_MALOAISP START WITH 1;
--INSERT DATA
SELECT * FROM LOAISANPHAM;
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Hoa hồng', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Mao lương', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Hoa cẩm chướng', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Cúc mẫu đơn', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Hoa mẫu đơn', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Hướng dương', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Cẩm tú cầu', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Tulip', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Đào', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Thủy tiên', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Hoa sen', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Hoa baby', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Tuyết mai', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Đồng tiền', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Salem', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Box hoa', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Giỏ hoa', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Hoa cưới', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Vòng wearth', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Thiệp', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Bình hoa', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Giấy gói hoa', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Khung hoa', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Bó hoa', NULL);
INSERT INTO LOAISANPHAM VALUES(SEQ8_MALOAISP.NEXTVAL, N'Cài áo', NULL);

COMMIT;
--THÀNH CÔNG

