CREATE TABLE PHIEUNHAP (
    MAPHIEUNHAP NUMBER NOT NULL,
    MANCC NUMBER,
    NGAYNHAP DATE NOT NULL,
    MANV NUMBER NOT NULL,
    TONGTIENNHAP NUMBER DEFAULT 0,
    CONSTRAINT PK_PN PRIMARY KEY(MAPHIEUNHAP)
)
CREATE SEQUENCE SEQ3_MAPHIEUNHAP START WITH 1;
--INSERT DATA
SELECT * FROM PHIEUNHAP order by maphieunhap;

ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY HH24:Mi:SS';
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 1, '08/05/2022', 2); --DL
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 2, '03/05/2022', 9); --Giay
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 3, '03/05/2022', 9); --Binh
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 4, '07/05/2022', 4); --Nhập khẩu
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 1, '10/05/2022', 2); 
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 2, '07/05/2022', 9);--Giấy
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 3, '04/05/2022', 9);--Bình
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 4, '18/05/2022', 4);
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 4, '29/05/2022', 4);
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 1, '16/05/2022', 2);
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 5, '08/05/2022', 9); --Khung, Vòng wearth
INSERT INTO PHIEUNHAP(MAPHIEUNHAP, MANCC, NGAYNHAP, MANV) VALUES(SEQ3_MAPHIEUNHAP.NEXTVAL, 5, '16/05/2022', 9); --Khung, Vòng wearth

COMMIT;
--thành công
