-------------- lost update -----------
--SET TRANSACTION ISOLATION LEVEL Read committed;
--SELECT GIA FROM SANPHAM WHERE MASP = 4;
--
--UPDATE SANPHAM SET GIA = 40000 WHERE MASP = 4;
--
--COMMIT;
--SELECT GIA FROM SANPHAM WHERE MASP = 4;
/*Giải quyết*/
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
--SELECT GIA FROM SANPHAM WHERE MASP = 4;
--
--UPDATE SANPHAM SET GIA = 40000 WHERE MASP = 4;
--
--COMMIT;
--SELECT GIA FROM SANPHAM WHERE MASP = 4;

------------------- Non - repeatable read -----------------
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
--SELECT TICHLUY FROM KHACHHANG WHERE MAKH = 2;
--
--SELECT TICHLUY FROM KHACHHANG WHERE MAKH = 2;
--
--COMMIT;

-------------- Phantom read -----------
--SET TRANSACTION ISOLATION LEVEL Read committed;
--SELECT MASP, TENSP, GIA FROM SANPHAM WHERE GIA >= 500000;
--
--SELECT MASP, TENSP, GIA FROM SANPHAM WHERE GIA >= 500000;
--COMMIT;

-------------- Deadlock -----------
SET TRANSACTION ISOLATION LEVEL Read committed;
UPDATE SANPHAM SET GIA = 25000 WHERE MASP = 110;

UPDATE SANPHAM SET GIA = 20000 WHERE MASP = 111;
COMMIT;
















