CREATE TABLE CTHD (
    SOHD NUMBER NOT NULL,
    MASP NUMBER NOT NULL,
    SOLUONG NUMBER NOT NULL,
    CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MASP)
)

--INSERT DATA
SELECT * FROM CTHD;
DELETE FROM CTHD;

COMMIT;
--thành công