CREATE TABLE CTPN(
    MASP NUMBER NOT NULL,
    MAPHIEUNHAP NUMBER NOT NULL,
    SLNHAP NUMBER NOT NULL,
    GIANHAP NUMBER NOT NULL,
    CONSTRAINT PK_CTPN PRIMARY KEY (MAPHIEUNHAP, MASP)
)
--INSERT DATA
SELECT * FROM CTPN;
SELECT COUNT(*) FROM CTPN WHERE MAPHIEUNHAP =8;
SELECT SUM(SLNHAP*GIANHAP) FROM CTPN WHERE MAPHIEUNHAP =1;

COMMIT;
