CREATE TABLE HOADON (
    SOHD NUMBER NOT NULL,
    NGAYHD DATE NOT NULL,
    TONGTIEN NUMBER DEFAULT 0,
    MANV NUMBER NOT NULL,
    MAKH NUMBER, --MaKH có thể có giá trị NULL cho khách hàng không đky làm khách hàng thành viên.
    CHIETKHAU DECIMAL(10,2) DEFAULT 0,
    TRIGIAHD NUMBER DEFAULT 0,
    CONSTRAINT PK_HD PRIMARY KEY(SOHD)
)
DROP SEQUENCE SEQ7_SOHD;
CREATE SEQUENCE SEQ7_SOHD START WITH 76;
--INSERT DATA
SELECT * FROM HOADON;
DELETE FROM HOADON;
SELECT SUM(TRIGIAHD) FROM HOADON;

COMMIT;
--thành công
