CREATE TABLE KHACHHANG (
    MAKH NUMBER NOT NULL,
    HOTEN NVARCHAR2(50) NOT NULL,
    SDT VARCHAR2(20) NOT NULL UNIQUE,
    DIACHI NVARCHAR2(255) NULL,
    NGAYSINH DATE NOT NULL,
    NGAYDK DATE NOT NULL,
    LOAIKH VARCHAR2(20) DEFAULT N'Moi',
    TICHLUY NUMBER DEFAULT 0,
    GHICHU NVARCHAR2(255),
    GIOITINH NVARCHAR2(10) NOT NULL,
    CONSTRAINT PK_KH PRIMARY KEY(MAKH)
)
DROP SEQUENCE SEQ1_MAKH;
CREATE SEQUENCE SEQ1_MAKH START WITH 1;
ALTER TABLE KHACHHANG MODIFY LOAIKH DEFAULT N'Moi';
SELECT * FROM khachhang;
DELETE FROM KHACHHANG;
--INSERT DATA
COMMIT;