CREATE TABLE KHUYENMAI (
    MAKM NUMBER NOT NULL,
    TENKM NVARCHAR2(255) NOT NULL,
    PHANTRAM DECIMAL(10,2) NOT NULL,
    NGAYBD DATE,
    NGAYKT DATE,
    CONSTRAINT PK_KM PRIMARY KEY(MAKM)
)
CREATE SEQUENCE SEQ6_MAKM START WITH 1;

--INSERT DATA
SELECT * FROM KHUYENMAI;
COMMIT;