CREATE TABLE LUONG(
    THANG NUMBER NOT NULL,
    NAM NUMBER NOT NULL,
    MANV NUMBER NOT NULL,
    SOGIOLAMTC NUMBER DEFAULT 0,
    SOGIOLAMTT NUMBER DEFAULT 0,
    LUONG DECIMAL(15,3) DEFAULT 0,
    CONSTRAINT PK_LUONG PRIMARY KEY(THANG, NAM, MANV)
)
--INSERT DATA
SELECT * FROM LUONG;
DELETE FROM LUONG;
/*=================== Tính Lương Tháng 5 cho nhân viên ======================*/
INSERT INTO LUONG(THANG, NAM, MANV) VALUES(5, 2022, 1);
INSERT INTO LUONG(THANG, NAM, MANV) VALUES(5, 2022, 2);
INSERT INTO LUONG(THANG, NAM, MANV) VALUES(5, 2022, 3);
INSERT INTO LUONG(THANG, NAM, MANV) VALUES(5, 2022, 4);
INSERT INTO LUONG(THANG, NAM, MANV) VALUES(5, 2022, 5);
INSERT INTO LUONG(THANG, NAM, MANV) VALUES(5, 2022, 6);
INSERT INTO LUONG(THANG, NAM, MANV) VALUES(5, 2022, 7);
INSERT INTO LUONG(THANG, NAM, MANV) VALUES(5, 2022, 8);
INSERT INTO LUONG(THANG, NAM, MANV) VALUES(5, 2022, 9);
INSERT INTO LUONG(THANG, NAM, MANV) VALUES(5, 2022, 10);

COMMIT;
--thành công
