CREATE TABLE PHIEUNHAP (
    MAPHIEUNHAP NUMBER NOT NULL,
    MANCC NUMBER,
    NGAYNHAP DATE NOT NULL,
    MANV NUMBER NOT NULL,
    TONGTIENNHAP NUMBER DEFAULT 0,
    CONSTRAINT PK_PN PRIMARY KEY(MAPHIEUNHAP)
)
DROP SEQUENCE SEQ3_MAPHIEUNHAP;
CREATE SEQUENCE SEQ3_MAPHIEUNHAP START WITH 1;
--INSERT DATA
SELECT * FROM PHIEUNHAP;
DELETE FROM PHIEUNHAP;
ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY HH24:Mi:SS';

COMMIT;
--thành công