CREATE TABLE SANPHAM(
    MASP NUMBER NOT NULL,
    TENSP NVARCHAR2(60) NOT NULL UNIQUE,
    GIA NUMBER NOT NULL,
    MALOAISP NUMBER NOT NULL,
    MAUSAC NVARCHAR2(100) NULL,
    SLSAN NUMBER DEFAULT 0,
    GHICHU NVARCHAR2(255),
    ANHSP NVARCHAR2(255) NOT NULL,
    CONSTRAINT PK_SP PRIMARY KEY(MASP)
)
DROP SEQUENCE SEQ2_MASP;
CREATE SEQUENCE SEQ2_MASP START WITH 6;

--INSERT DATA
SELECT * FROM SANPHAM;
DELETE FROM SANPHAM;
COMMIT;
