/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import BUS.DoiTacBUS;
import BUS.NhanVienBUS;
import BUS.NhapHangBUS;
import BUS.SanPhamBUS;
import DTO.NhapHang;
import static View.SuaNhanVien_QL.isNumeric;
import java.awt.HeadlessException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class ThemNhapHang extends javax.swing.JFrame {

    /**
     * Creates new form ThemNhapHang_QL
     */
    String user;
    String ngayNhapHang = null;
    ArrayList<Object> arrObj = new ArrayList<Object>();
    String tenSPAdd = null;
    public ThemNhapHang(String a)throws HeadlessException {
        initComponents();
        setLocationRelativeTo(null);
        this.user = a;
        loadTenSP();
        loadTenNCC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        AddInsert = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cbbTenSP = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        datePickerNgNhap = new com.github.lgooddatepicker.components.DatePicker();
        txtSLNhap = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddIntoTable = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cbbTenNCC = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        QLNV = new javax.swing.JButton();
        ChungBtn = new javax.swing.JButton();
        QLSP = new javax.swing.JButton();
        QLKH = new javax.swing.JButton();
        QLDT = new javax.swing.JButton();
        QLKM = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        QLHD = new javax.swing.JButton();
        QLDS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm nhập hàng");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(249, 255, 254));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageText/tag/Nhập hàng.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageText/tag/Đăng xuất.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        Back.setBackground(new java.awt.Color(249, 255, 254));
        Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(196, 100, 96));
        Back.setText("Quay lại");
        Back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(196, 100, 96), 1, true));
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.setFocusPainted(false);
        Back.setFocusable(false);
        Back.setRequestFocusEnabled(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        AddInsert.setBackground(new java.awt.Color(196, 100, 96));
        AddInsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddInsert.setForeground(new java.awt.Color(255, 255, 255));
        AddInsert.setText("Nhập hàng");
        AddInsert.setBorder(null);
        AddInsert.setBorderPainted(false);
        AddInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddInsert.setFocusPainted(false);
        AddInsert.setRequestFocusEnabled(false);
        AddInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInsertActionPerformed(evt);
            }
        });

        jLabel11.setText("Ngày nhập");
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));

        cbbTenSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001", "002", "003", "004" }));
        cbbTenSP.setBackground(new java.awt.Color(249, 255, 254));
        cbbTenSP.setFocusable(false);
        cbbTenSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTenSP.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setText("Tên SP");
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));

        txtSLNhap.setBackground(new java.awt.Color(249, 255, 254));
        txtSLNhap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSLNhap.setCaretColor(new java.awt.Color(0, 0, 0));
        txtSLNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSLNhap.setForeground(new java.awt.Color(0, 0, 0));
        txtSLNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLNhapActionPerformed(evt);
            }
        });

        jLabel13.setText("Số lượng nhập");
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));

        txtGiaNhap.setBackground(new java.awt.Color(249, 255, 254));
        txtGiaNhap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtGiaNhap.setCaretColor(new java.awt.Color(0, 0, 0));
        txtGiaNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGiaNhap.setForeground(new java.awt.Color(0, 0, 0));

        jLabel14.setText("Giá nhập");
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));

        jButton13.setText("Thêm SP mới");
        jButton13.setBackground(new java.awt.Color(196, 100, 96));
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setFocusPainted(false);
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setRequestFocusEnabled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên SP", "Ngày nhập", "SL nhập", "Giá nhập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Long.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setBackground(new java.awt.Color(180, 222, 197));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(196, 100, 96));
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        AddIntoTable.setText("Thêm");
        AddIntoTable.setBackground(new java.awt.Color(196, 100, 96));
        AddIntoTable.setBorder(null);
        AddIntoTable.setBorderPainted(false);
        AddIntoTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddIntoTable.setFocusPainted(false);
        AddIntoTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddIntoTable.setForeground(new java.awt.Color(255, 255, 255));
        AddIntoTable.setRequestFocusEnabled(false);
        AddIntoTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIntoTableActionPerformed(evt);
            }
        });

        jLabel15.setText("Tên NCC");
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));

        cbbTenNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001", "002", "003", "004" }));
        cbbTenNCC.setBackground(new java.awt.Color(249, 255, 254));
        cbbTenNCC.setFocusable(false);
        cbbTenNCC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTenNCC.setForeground(new java.awt.Color(0, 0, 0));
        cbbTenNCC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTenNCCItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(AddIntoTable, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(cbbTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(cbbTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSLNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(401, 401, 401)
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(datePickerNgNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbbTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(38, 38, 38))
                        .addComponent(txtSLNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(cbbTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datePickerNgNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(3, 3, 3)
                        .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(AddIntoTable, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 760, 640));

        jPanel1.setBackground(new java.awt.Color(231, 238, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageText/tag/logo nhỏ.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 25, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(85, 122, 100));
        jSeparator1.setForeground(new java.awt.Color(85, 122, 100));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 72, 216, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageText/tag/Chung.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        QLNV.setText("Nhân viên");
        QLNV.setBackground(new java.awt.Color(231, 238, 237));
        QLNV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(196, 100, 96), 1, true));
        QLNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QLNV.setFocusable(false);
        QLNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        QLNV.setForeground(new java.awt.Color(196, 100, 96));
        QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLNVActionPerformed(evt);
            }
        });
        jPanel1.add(QLNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 198, 151, 40));

        ChungBtn.setText("Chung");
        ChungBtn.setBackground(new java.awt.Color(231, 238, 237));
        ChungBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(196, 100, 96), 1, true));
        ChungBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChungBtn.setFocusPainted(false);
        ChungBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ChungBtn.setForeground(new java.awt.Color(196, 100, 96));
        ChungBtn.setRequestFocusEnabled(false);
        ChungBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChungBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ChungBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 146, 151, 40));

        QLSP.setText("Sản phẩm");
        QLSP.setBackground(new java.awt.Color(231, 238, 237));
        QLSP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(196, 100, 96), 1, true));
        QLSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QLSP.setFocusable(false);
        QLSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        QLSP.setForeground(new java.awt.Color(196, 100, 96));
        QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSPActionPerformed(evt);
            }
        });
        jPanel1.add(QLSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 250, 151, 40));

        QLKH.setText("Khách hàng");
        QLKH.setBackground(new java.awt.Color(231, 238, 237));
        QLKH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(196, 100, 96), 1, true));
        QLKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QLKH.setFocusable(false);
        QLKH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        QLKH.setForeground(new java.awt.Color(196, 100, 96));
        QLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLKHActionPerformed(evt);
            }
        });
        jPanel1.add(QLKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 302, 151, 40));

        QLDT.setText("Đối tác");
        QLDT.setBackground(new java.awt.Color(231, 238, 237));
        QLDT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(196, 100, 96), 1, true));
        QLDT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QLDT.setFocusable(false);
        QLDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        QLDT.setForeground(new java.awt.Color(196, 100, 96));
        QLDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLDTActionPerformed(evt);
            }
        });
        jPanel1.add(QLDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 354, 151, 40));

        QLKM.setText("Khuyến mãi");
        QLKM.setBackground(new java.awt.Color(231, 238, 237));
        QLKM.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(196, 100, 96), 1, true));
        QLKM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QLKM.setFocusable(false);
        QLKM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        QLKM.setForeground(new java.awt.Color(196, 100, 96));
        QLKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLKMActionPerformed(evt);
            }
        });
        jPanel1.add(QLKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 406, 151, 40));

        jButton7.setText("Nhập hàng");
        jButton7.setBackground(new java.awt.Color(196, 100, 96));
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusable(false);
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 458, 151, 40));

        QLHD.setText("Hóa đơn");
        QLHD.setBackground(new java.awt.Color(231, 238, 237));
        QLHD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(196, 100, 96), 1, true));
        QLHD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QLHD.setFocusable(false);
        QLHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        QLHD.setForeground(new java.awt.Color(196, 100, 96));
        QLHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLHDActionPerformed(evt);
            }
        });
        jPanel1.add(QLHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 510, 151, 40));

        QLDS.setText("Doanh thu");
        QLDS.setBackground(new java.awt.Color(231, 238, 237));
        QLDS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(196, 100, 96), 1, true));
        QLDS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QLDS.setFocusable(false);
        QLDS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        QLDS.setForeground(new java.awt.Color(196, 100, 96));
        QLDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLDSActionPerformed(evt);
            }
        });
        jPanel1.add(QLDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 562, 151, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int checkChucVu() {
        NhanVienBUS bus = new NhanVienBUS();
        String chucVu = bus.getChucVu(user);
        if (chucVu.equals("Quản lý")) {
            return 1;
        } else if (chucVu.equals("Thu ngân")) {
            return 2;
        } else if (chucVu.equals("Bán hàng")) {
            return 3;
        } else {
            return 4;
        }
    }
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        hide();
        WelcomeScreen.main(null);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLNVActionPerformed
        // TODO add your handling code here:
        hide();
        if (checkChucVu() == 1) {
            TraCuuNhanVien_QL.main(user);
        } else {
            NhanVien_KhongTruyCap_NV.main(user);
        }
    }//GEN-LAST:event_QLNVActionPerformed

    private void ChungBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChungBtnActionPerformed
        // TODO add your handling code here:
        hide();
        Chung.main(user);
    }//GEN-LAST:event_ChungBtnActionPerformed

    private void QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSPActionPerformed
        // TODO add your handling code here:
        hide();
        switch (checkChucVu()) {
            case 1:
            case 4:
                TraCuuSanPham_QL.main(user);
                break;
            case 2:
            case 3:
                TraCuuSanPham_NV.main(user);
                break;
            default:
                SanPham_KhongTruyCap_NV.main(user);
                break;
        }
    }//GEN-LAST:event_QLSPActionPerformed

    private void QLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLKHActionPerformed
        // TODO add your handling code here:
        hide();
        switch (checkChucVu()) {
            case 1:
            case 2:
            TraCuuKhachHang.main(user);
            break;
            case 3:
            TraCuuKhachHang_NV.main(user);
            break;
            default:
            KhachHang_KhongTruyCap_NV.main(user);
            break;
        }
    }//GEN-LAST:event_QLKHActionPerformed

    private void QLDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLDTActionPerformed
        // TODO add your handling code here:
        hide();
        if (checkChucVu() == 1) {
            TraCuuDoiTac_QL.main(user);
        } else {
            DoiTac_KhongTruyCap_NV.main(user);
        }
    }//GEN-LAST:event_QLDTActionPerformed

    private void QLKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLKMActionPerformed
        // TODO add your handling code here:
        hide();
        switch (checkChucVu()) {
            case 1:
            TraCuuKhuyenMai_QL.main(user);
            break;
            case 2:
            TraCuuKhuyenMai_NV.main(user);
            break;
            default:
            KhuyenMai_KhongTruyCap_NV.main(user);
            break;
        }
    }//GEN-LAST:event_QLKMActionPerformed

    private void QLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLHDActionPerformed
        // TODO add your handling code here:
        hide();
        switch (checkChucVu()) {
            case 1:
            case 2:
            TraCuuHoaDon.main(user);
            break;
            case 3:
            TraCuuHoaDon_NV.main(user);
            break;
            default:
            HoaDon_KhongTruyCap_NV.main(user);
            break;
        }
    }//GEN-LAST:event_QLHDActionPerformed

    private void QLDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLDSActionPerformed
        // TODO add your handling code here:
        hide();
        if (checkChucVu() == 1) {
            DoanhThu_LuaChon_QL.main(user);
        } else {
            DoanhThu_KhongTruyCap_NV.main(user);
        }
    }//GEN-LAST:event_QLDSActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        hide();
        TraCuuNhapHang.main(user);
    }//GEN-LAST:event_BackActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        hide();
        ThemSanPham.main(user);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void txtSLNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLNhapActionPerformed

    public void clearNH() {
        txtGiaNhap.setText("");
        txtSLNhap.setText("");
        datePickerNgNhap.setDate(null);
        cbbTenSP.setSelectedIndex(0);
    }
    
    public void clearTB() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        arrObj.clear();
    }
    
    private void AddInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInsertActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn nhập hàng?", "Xác nhận",JOptionPane.YES_NO_OPTION );
        if (reply == JOptionPane.NO_OPTION || reply == JOptionPane.CLOSED_OPTION) {
            return;
        }
        
        try {
            NhapHangBUS busNH = new NhapHangBUS();
            SanPhamBUS busSP = new SanPhamBUS();
            DoiTacBUS busDT = new DoiTacBUS();
            Object[] firstRow = (Object[]) arrObj.get(0);
            int ma = 0;
            String ngNhapHang = firstRow[3].toString();
            DateTimeFormatter fIn = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate ldNgNhap = LocalDate.parse(ngNhapHang, fIn);
            int maNV = Integer.parseInt(user);
            int maDT = busDT.getMaDT(firstRow[1].toString());
            int maSP = busSP.getMaSP(firstRow[2].toString());
            int SLnhap = Integer.parseInt(firstRow[4].toString());
            long giaNhap = Long.parseLong(firstRow[5].toString());
            NhapHang kh = new NhapHang(ma, maNV, maSP, maDT, SLnhap, ldNgNhap, 0, giaNhap);
            
            if (busNH.insertNH(kh)) {
                if (busNH.getMaPN() != 0) {
                    Object[] row = null;
                    boolean nhaphangCTPN = false;
                    boolean nhaphangCungCap = false;
                    for (int i = 0; i < arrObj.size(); i++) {
                        row = (Object[]) arrObj.get(i);
                        int maDTRow = busDT.getMaDT(row[1].toString());
//                        if (maDTRow )
                        int maSPRow = busSP.getMaSP(row[2].toString());
                        int SLNhapRow = Integer.parseInt(row[4].toString());
                        long giaNhapRow = Long.parseLong(row[5].toString());
                        NhapHang rowNH = new NhapHang(busNH.getMaPN(), maNV, maSPRow, maDTRow, SLNhapRow, ldNgNhap, 0, giaNhapRow);
                        nhaphangCTPN = busNH.insertCTPN(rowNH);
                        nhaphangCungCap = busNH.insertCungCap(rowNH);
                    }
                    if (nhaphangCTPN && nhaphangCungCap) {
                        JOptionPane.showMessageDialog(this, "Đã nhập hàng thành công!");
                        datePickerNgNhap.setEnabled(true);
                        clearTB();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi, vui lòng thử lại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddInsertActionPerformed

    private void AddIntoTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIntoTableActionPerformed
        // TODO add your handling code here:
        String slnhap = txtSLNhap.getText();
        String ngnhap = null;
        if (datePickerNgNhap.isEnabled()) {
            ngnhap = String.format("%1$td/%1$tm/%1$tY", datePickerNgNhap.getDate());
        }
        String tenNCC = cbbTenNCC.getSelectedItem().toString();
        tenSPAdd = cbbTenSP.getSelectedItem().toString();
        String gianhap = txtGiaNhap.getText();
        
        if (datePickerNgNhap.isEnabled()) {
            if (ngnhap.equals("null/null/null") ) {
                JOptionPane.showMessageDialog(this, "Thông tin không được để trống", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (slnhap.equals("") || tenSPAdd.equals("") || gianhap.equals("") || tenNCC.equals("")) {
            JOptionPane.showMessageDialog(this, "Thông tin không được để trống", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!isNumeric(txtSLNhap.getText()) || !isNumeric(txtGiaNhap.getText())) {
            JOptionPane.showMessageDialog(this, "Hãy nhập vào 1 số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        Object [] rowCheck = null;
        for (int i = 0; i < arrObj.size(); i++) {
            rowCheck = (Object[]) arrObj.get(i);
            String tenSPCheck = rowCheck[2].toString();
            if (tenSPAdd.equals(tenSPCheck)) {
                JOptionPane.showMessageDialog(this,"Bạn đã thêm sản phẩm này rồi!","Lỗi",JOptionPane.ERROR_MESSAGE);
            return;
            }
        }
        int reply = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thêm?", "Xác nhận",JOptionPane.YES_NO_OPTION );
        if (reply == JOptionPane.NO_OPTION || reply == JOptionPane.CLOSED_OPTION) {
            return;
        }
        
        if (ngnhap != null) {
            datePickerNgNhap.setEnabled(false);
            ngayNhapHang = ngnhap;
        }
        
        Object[] row = {user, tenNCC, tenSPAdd, ngayNhapHang, slnhap, gianhap};
        arrObj.add(row);
        JOptionPane.showMessageDialog(this, "Đã thêm thành công!");
        clearNH();
        loadTable();
        System.out.println("arrObj: " + arrObj);
    }//GEN-LAST:event_AddIntoTableActionPerformed

    private void cbbTenNCCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTenNCCItemStateChanged
        // TODO add your handling code here:
        loadTenSP();
    }//GEN-LAST:event_cbbTenNCCItemStateChanged

    public void loadTable() {
        String[] header = {"Mã NV","Tên NCC", "Tên SP", "Ngày nhập", "SL nhập", "Giá nhập"};
        DefaultTableModel dtm = new DefaultTableModel(header, 0);
        Object[] row = null;
        for (int i = 0; i < arrObj.size(); i++) {
            row = (Object[]) arrObj.get(i);
            dtm.addRow(row);
        }
        jTable1.setModel(dtm);
    }
    
    public void loadTenSP() {
        ArrayList<String> arr = new ArrayList<String>();
        arr = SanPhamBUS.getTenSP();
        cbbTenSP.setModel(new DefaultComboBoxModel(arr.toArray()));
    }
    
    public void loadTenNCC() {
        ArrayList<String> arr = new ArrayList<String>();
        arr = DoiTacBUS.getTenDT();
        cbbTenNCC.setModel(new DefaultComboBoxModel(arr.toArray()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemNhapHang(args).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddInsert;
    private javax.swing.JButton AddIntoTable;
    private javax.swing.JButton Back;
    private javax.swing.JButton ChungBtn;
    private javax.swing.JButton QLDS;
    private javax.swing.JButton QLDT;
    private javax.swing.JButton QLHD;
    private javax.swing.JButton QLKH;
    private javax.swing.JButton QLKM;
    private javax.swing.JButton QLNV;
    private javax.swing.JButton QLSP;
    private javax.swing.JComboBox<String> cbbTenNCC;
    private javax.swing.JComboBox<String> cbbTenSP;
    private com.github.lgooddatepicker.components.DatePicker datePickerNgNhap;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtSLNhap;
    // End of variables declaration//GEN-END:variables
}
