CREATE TABLE CTPN(
    MASP NUMBER NOT NULL,
    MAPHIEUNHAP NUMBER NOT NULL,
    SLNHAP NUMBER NOT NULL,
    GIANHAP NUMBER NOT NULL,
    CONSTRAINT PK_CTPN PRIMARY KEY (MAPHIEUNHAP, MASP)
)
--INSERT DATA
SELECT * FROM CTPN;

