CREATE TABLE HOADON (
    SOHD NUMBER NOT NULL,
    NGAYHD DATE NOT NULL,
    TONGTIEN NUMBER DEFAULT 0,
    MANV NUMBER NOT NULL,
    MAKH NUMBER, --MAKH co the null de luu nhung khach hang khong dktv
    CHIETKHAU DECIMAL(10,2) DEFAULT 0,
    TRIGIAHD NUMBER DEFAULT 0,
    GHICHU NVARCHAR2(255),
    CONSTRAINT PK_HD PRIMARY KEY(SOHD)
)
CREATE SEQUENCE SEQ7_SOHD START WITH 1;
--INSERT DATA
SELECT * FROM HOADON;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
