CREATE TABLE KHACHHANG (
    MAKH NUMBER NOT NULL,
    HOTEN NVARCHAR2(50) NOT NULL,
    SDT VARCHAR2(20) NOT NULL UNIQUE,
    DIACHI NVARCHAR2(255) NOT NULL,
    NGAYSINH DATE NOT NULL,
    NGAYDK DATE NOT NULL,
    LOAIKH NVARCHAR2(20) DEFAULT N'Bình thường',
    TICHLUY NUMBER DEFAULT 0,
    GHICHU NVARCHAR2(255),
    GIOITINH NVARCHAR2(10) NOT NULL,
    CONSTRAINT PK_KH PRIMARY KEY(MAKH)
)
CREATE SEQUENCE SEQ1_MAKH START WITH 1;
SELECT * FROM khachhang;
