CREATE TABLE KHUYENMAI (
    MAKM VARCHAR2(255) PRIMARY KEY,
    TENKM NVARCHAR2(255),
    PHANTRAM DECIMAL
)

--INSERT DATA
SELECT * FROM KHUYENMAI;
INSERT INTO KHUYENMAI VALUES('BDCTETNGUYENDAN', N'Gi?m Giá 15% Nhân D?p T?t Nguyên ?án', 0.15);
INSERT INTO KHUYENMAI VALUES('BDCTETNGUYENDANVIP', N'Gi?m Giá 20% Nhân D?p T?t Nguyên ?án', 0.20);
INSERT INTO KHUYENMAI VALUES('BDCTETNGUYENDANLUX', N'Gi?m Giá 25% Nhân D?p T?t Nguyên ?án', 0.25);
INSERT INTO KHUYENMAI VALUES('BDCPHUNU8T3', N'M?ng Ngày Qu?c T? Ph? N?', 0.05);
INSERT INTO KHUYENMAI VALUES('BDCPHUNU20T10', N'M?ng Ngày Ph? N? Vi?t Nam', 0.1);
INSERT INTO KHUYENMAI VALUES('BDCSINHNHATBDC', N'Sinh Nh?t C?a Hàng', 0.15);
INSERT INTO KHUYENMAI VALUES('BDCSINHNHAT', N'Chúc M?ng Sinh Nh?t Khách Hàng', 0.15);
INSERT INTO KHUYENMAI VALUES('BDCTET', N'Chúc M?ng T?t', 0.15);
INSERT INTO KHUYENMAI VALUES('BDC07TCS23', N'Ngày Vui', 0.05);