CREATE TABLE LOAISANPHAM (
    MALOAISP NUMBER NOT NULL,
    TENLOAISP NVARCHAR2(100) NOT NULL,
    GHICHU NVARCHAR2(255),
    CONSTRAINT PK_LOAISP PRIMARY KEY(MALOAISP)
)

CREATE SEQUENCE SEQ8_MALOAISP START WITH 1;