CREATE TABLE NHACUNGCAP(
    MANCC NUMBER NOT NULL,
    TENNCC NVARCHAR2(255) NOT NULL,
    DIACHI NVARCHAR2(255) NOT NULL,
    SDT VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_NCC PRIMARY KEY(MANCC)
)
CREATE SEQUENCE SEQ5_MANCC START WITH 1;

--INSERT DATA
SELECT * FROM NHACUNGCAP;