CREATE TABLE NHANVIEN(
    MANV NUMBER NOT NULL,
    HOTEN NVARCHAR2(255) NOT NULL,
    DIACHI NVARCHAR2(255) NOT NULL,
    SDT VARCHAR2(20) NOT NULL,
    CMND VARCHAR(30) NOT NULL UNIQUE,
    NGAYSINH DATE NOT NULL,
    NGAYVL DATE NOT NULL,
    LUONGCOBAN NUMBER NOT NULL,
    CHUCVU NVARCHAR2(255) NOT NULL,
    GIOITINH NVARCHAR2(10) NOT NULL,
    CONSTRAINT PK_NV PRIMARY KEY(MANV)
)
CREATE SEQUENCE SEQ4_MANV START WITH 1;
--INSERT DATA
SELECT * FROM NHANVIEN;
ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY HH24:MI:SS';
