CREATE TABLE SANPHAM(
    MASP NUMBER NOT NULL,
    TENSP NVARCHAR2 (60) NOT NULL UNIQUE,
    GIA NUMBER NOT NULL,
    MALOAISP NUMBER NOT NULL,
    MAUSAC NVARCHAR2(100) NOT NULL,
    SLSAN NUMBER DEFAULT 0,
    GHICHU NVARCHAR2(255),
    CONSTRAINT PK_SP PRIMARY KEY(MASP)
)
CREATE SEQUENCE SEQ2_MASP START WITH 1;

--INSERT DATA
SELECT * FROM SANPHAM;

