CREATE TABLE CTKM (
    SOHD NUMBER NOT NULL,
    MAKM NUMBER NOT NULL,
    CONSTRAINT PK_CTKM PRIMARY KEY (SOHD, MAKM)
)

--INSERT DATA
SELECT * FROM CTKM;

/*==================== Thêm khuyến mãi cho hóa đơn - CTKM ====================*/
--Ngày 27/5
SELECT * FROM CTKM;
INSERT INTO CTKM(SOHD, MAKM) VALUES(1, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(2, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(3, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(4, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(5, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(6, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(7, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(8, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(9, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(10, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(11, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(12, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(13, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(14, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(15, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(16, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(17, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(18, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(19, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(20, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(21, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(22, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(23, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(24, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(25, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(26, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(27, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(28, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(29, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(30, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(31, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(32, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(33, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(34, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(35, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(36, 2);

--Ngày 28/5
INSERT INTO CTKM(SOHD, MAKM) VALUES(37, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(38, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(39, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(40, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(41, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(42, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(43, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(44, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(45, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(46, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(47, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(48, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(49, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(50, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(51, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(52, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(53, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(54, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(55, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(56, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(57, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(58, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(59, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(60, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(61, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(62, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(63, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(64, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(66, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(67, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(68, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(69, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(70, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(74, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(75, 2);

--Ngày 29/5
INSERT INTO CTKM(SOHD, MAKM) VALUES(76, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(77, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(78, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(79, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(80, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(81, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(82, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(83, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(84, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(85, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(86, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(87, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(88, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(89, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(90, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(91, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(92, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(93, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(94, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(95, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(96, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(97, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(98, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(99, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(100, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(101, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(102, 2);

INSERT INTO CTKM(SOHD, MAKM) VALUES(103, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(104, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(105, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(106, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(107, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(108, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(109, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(110, 2);

INSERT INTO CTKM(SOHD, MAKM) VALUES(111, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(112, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(113, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(114, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(115, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(116, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(117, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(118, 2);

INSERT INTO CTKM(SOHD, MAKM) VALUES(119, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(120, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(121, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(122, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(123, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(124, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(125, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(126, 2);

INSERT INTO CTKM(SOHD, MAKM) VALUES(127, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(130, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(131, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(132, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(133, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(134, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(135, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(136, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(137, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(138, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(139, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(140, 2);
INSERT INTO CTKM(SOHD, MAKM) VALUES(141, 2);

COMMIT;




