CREATE TABLE HOADON (
    SOHD NUMBER NOT NULL,
    NGAYHD DATE NOT NULL,
    TONGTIEN NUMBER DEFAULT 0,
    MANV NUMBER NOT NULL,
    MAKH NUMBER, --MAKH co the null de luu nhung khach hang khong dktv
    CHIETKHAU DECIMAL(10,2) DEFAULT 0,
    TRIGIAHD NUMBER DEFAULT 0,
    CONSTRAINT PK_HD PRIMARY KEY(SOHD)
)
CREATE SEQUENCE SEQ7_SOHD START WITH 1;
SELECT * FROM HOADON;
--INSERT DATA
SELECT * FROM HOADON order by sohd;
--Ngày 27/5 
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 1);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 2);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 3);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 4);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 5);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 6);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 7);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 8);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 9);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 10);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 11);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 12);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 13);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 14);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 15);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 16);

--Ngày 28/5 
COMMIT;
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 17);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 18);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 19);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 20);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 21);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 22);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 23);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 24);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 25);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 26);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 27);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 28);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 29);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 30);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 31);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 32);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 33);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 34);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 35);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 38);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);

--Ngày 29/5
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 36);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 37);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 38);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 39);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 40);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 41);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 42);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 43);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 44);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 45);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 45);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 46);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 47);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 48);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);

--Ngày 30/5
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 49);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 50);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 51);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 52);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 53);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, 54);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 55);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 56);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 9, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);

--Ngày 31/5 
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 5, 57);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 5, 58);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 5, 59);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 23);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 5, 54);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 19);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 12);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 56);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 5, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 7, 23);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 6);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, NULL);
INSERT INTO HOADON(SOHD, MANV, MAKH) VALUES(SEQ7_SOHD.NEXTVAL, 8, 34);

COMMIT;